### ISSUE TITLE
32-bit-build failures in glusterfs in test suits upstream

### ISSUE THREAD

**Issue by Shwetha-Acharya** [gluster/project-infrastructure#132]
The patches with 32-bit-build failures can be found [here](https://github.com/gluster/glusterfs/pulls)

**Comment by schaffung** [comment]
The failure is caused due to warnings treated as errors and certain warning being raised around getcwd. This was fixed in devel branch recently. Sent a backport to release-9 branch to fix the issue. Post its merging, we just need to rebase the other backports. For reference the backport solving the issue : https://github.com/gluster/glusterfs/pull/2549

**Comment by Shwetha-Acharya** [comment]
closing the issue as the problem is solved
