### ISSUE TITLE
gf_32-bit-build-smoke and gh_strfmt_errors jobs are failing

### ISSUE THREAD

**Issue by nik-redhat** [gluster/project-infrastructure#154]
The jobs [gf_32-bit-build-smoke](https://build.gluster.org/job/gh_32-bit-build-smoke/) and [gf_strfmt_errors](https://build.gluster.org/job/gh_strfmt_errors/) is failing since few days.

**Comment by nik-redhat** [comment]
@mscherer , @deepshikhaaa can you guys take a look?
TIA

**Comment by mscherer** [comment]
yep, it was discussed during meeting, @rakshithakamath94 brought it up. It seems the main cause is that Fedora 33 is EOL, so we need to switch a newer base. 

But since Fedora is dropping 32 bits sooner or later (see https://fedoramagazine.org/in-fedora-31-32-bit-i686-is-86ed/ ), we also have to discuss on a log term strategy here for what do we do when this happen.

**Comment by mscherer** [comment]
So, it should now work, if I am not wrong. We moved to F34 as there is a bug in F35 that prevent build with -Wall -Werror (see https://github.com/gluster/project-infrastructure/issues/150).

**Comment by rakshithakamath94** [comment]
The jobs are fixed and its running successfully. This issue can be closed!
